Repository mukulbbhardwaj/create-contact-card-HF22, pull requests merged in 2022-10, with the labels that each got.

#9 Pritam Das's card
  Pritam Das/index.html
  Pritam Das/script.js
  Pritam Das/style.css
Labels: hacktoberfest-accepted

#10 New Commits
  Github Hacktoberfest/README.md
  Github Hacktoberfest/assests/discord.png
  Github Hacktoberfest/assests/github.png
  Github Hacktoberfest/assests/linkedin.png
  Github Hacktoberfest/assests/man.png
  Github Hacktoberfest/assests/youtube.png
  Github Hacktoberfest/index.html
  Github Hacktoberfest/style.css
Labels: hacktoberfest-accepted

#11 Contact card created
  Krunal-Karena/Contact card.css
  Krunal-Karena/Contact card.html
  Krunal-Karena/Photo.jpg
  Krunal-Karena/cover image.jpg
  Krunal-Karena/geo-alt.svg
Labels: hacktoberfest-accepted

#12 Uploading my contact card
  manish_contact_card/index.html
  manish_contact_card/style.css
Labels: hacktoberfest-accepted

#13 #Contact Card created by Amisha Kumari.
  amisha-contact-card/contact.css
  amisha-contact-card/girl_picture.jpg
  amisha-contact-card/index.html
Labels: hacktoberfest-accepted

#16 Add files via upload
  card/assests/hater_fr.png
  card/assests/instagram.png
  card/assests/linkedin.png
  card/assests/profile.png
  card/assests/twitter.png
  card/index.html
  card/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#17 Card
  Suryansh Card/css/card.css
  Suryansh Card/image/20220611_201609.jpg
  Suryansh Card/image/file.png
  Suryansh Card/image/images.jpg
  Suryansh Card/image/linkedin.png
  Suryansh Card/image/mail.png
  Suryansh Card/image/planet-earth.png
  Suryansh Card/index.html
Labels: hacktoberfest, hacktoberfest-accepted

#20 Update script.js
  Pritam Das/script.js
Labels: hacktoberfest, hacktoberfest-accepted

#21 Add files via upload
  Vaibhav Aggarwal/viewProduct.html
Labels: hacktoberfest, hacktoberfest-accepted

#22 Made changes to CSS style and HTML
  Github Hacktoberfest/index.html
  Github Hacktoberfest/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#23 Update index.html
  Github Hacktoberfest/index.html
Labels: hacktoberfest, hacktoberfest-accepted

#26 Create index.html
  jay-card/index.html
Labels: hacktoberfest-accepted

#24 aditya ahirwar
  aditya-ahirwar/index.html
  aditya-ahirwar/resources/github.png
  aditya-ahirwar/resources/gmail.png
  aditya-ahirwar/resources/insta.png
  aditya-ahirwar/resources/linkedin.png
  aditya-ahirwar/resources/profile.jpg
  aditya-ahirwar/style.css
  contact card/index.html
Labels: hacktoberfest, hacktoberfest-accepted

#28 Create index.html
  rock-card/index.html
Labels: hacktoberfest, hacktoberfest-accepted

#31 Update Contributors-list.md
  Contributors-list.md
Labels: documentation

#30 Added contact card
  AbhishekJadhav2002/index.html
  AbhishekJadhav2002/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#32 Created Card
  awesome card/index.html
Labels: hacktoberfest, hacktoberfest-accepted

#33 initial commit
  ContactCard/DivyaKirad/back.png
  ContactCard/DivyaKirad/front.png
  ContactCard/DivyaKirad/img1.jpg
  ContactCard/DivyaKirad/index.html
  ContactCard/DivyaKirad/readme.md
  ContactCard/DivyaKirad/styles.css
Labels: hacktoberfest, hacktoberfest-accepted

#34 Create card
  ultra-card/index.html
Labels: hacktoberfest, hacktoberfest-accepted

#35 Update Contributors-list.md
  Contributors-list.md
Labels: hacktoberfest, hacktoberfest-accepted

#37 Update Contributors-list.md
  Contributors-list.md
Labels: hacktoberfest-accepted

#36 Create My Card
  my-card/index.html
Labels: hacktoberfest, hacktoberfest-accepted

#39 Add a contact card
  yasmin-contact-card/index.html
  yasmin-contact-card/photo.jpeg
Labels: hacktoberfest, hacktoberfest-accepted

#38 Change profile photo
  ultra-card/index.html
Labels: hacktoberfest, hacktoberfest-accepted

#40 Create index.html
  amit/index.html
Labels: hacktoberfest, hacktoberfest-accepted

#41 Create style.css
  amit/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#42 Update index.html
  amit/index.html
Labels: hacktoberfest, hacktoberfest-accepted

#44 Add files through upload
  Martin_Mohobo/Martin_Mohobo.html
  Martin_Mohobo/bkg3.jpg
  Martin_Mohobo/profile.jpg
  Martin_Mohobo/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#43 Create my card
  akash/index.html
Labels: hacktoberfest, hacktoberfest-accepted

#46 Contact Card
  theotsuaneng/IMG-9092.JPG
  theotsuaneng/jobCard.html
  theotsuaneng/jobCard.txt
Labels: hacktoberfest, hacktoberfest-accepted

#45 Added my contact card
  Nombasa-card/nombasa.html
Labels: hacktoberfest, hacktoberfest-accepted

#51 Add files via upload
  Ronaldo Gebashe/RonaldoG.html
  Ronaldo Gebashe/photo.jpg
Labels: hacktoberfest, hacktoberfest-accepted

#50 Updated Index.html
  amit/index.html
Labels: hacktoberfest, hacktoberfest-accepted

#49 created my card
  manali khattar/index.html
  manali khattar/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#54 Added my(Black) card
  Black Watch/index.html
  Black Watch/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#53 commit
  contact/index.html
  contact/my image.jpg
  contact/styles.css
Labels: hacktoberfest, hacktoberfest-accepted

#52 intital commit
  Contactme/bgimg.jpg
  Contactme/index.html
  Contactme/my image.jpg
  Contactme/mystyles.css
Labels: hacktoberfest, hacktoberfest-accepted

#56 Additional styling in awesome card
  .vscode/settings.json
  Black Watch/style.css
  awesome card/index.html
Labels: hacktoberfest, hacktoberfest-accepted
